%YAML 1.1
---
gfVersion: v1.0
class: workflow

# metadata
name: Bowtie2 workflow
description: Sequence alignment with Bowtie2
documentation_uri: 
repo_uri: 'https://github.com/jiangweiyao/bowtie2-workflow-gf.git'
version: '0.1'
username: jyao

final_output:
- align

# inputs
inputs:
  files:
    label: Reference Sequence FASTA File
    description: Reference Sequence FASTA File
    type: File
    default: /input/files.fastq
    enable: true
    visible: true
  reference:
    label: Reference Sequence FASTA
    description: Reference sequence FASTA file
    type: File
    default: /input/reference.fa
    enable: true
    visible: true

# parameters
parameters:
  threads:
    label: CPU Threads
    description: Number of CPU threads for alignment
    type: int
    default: 2
    enable: false
    visible: true

# steps
steps:
  index:
    app: apps/bowtie2-build-2.2.9-gf-0.2/app.yaml
    depend: []
    template:
      reference: '{workflow->reference}'
      output: reference

#  align:
#    app: apps/bwa-mem-0.7.17-gf-0.3/app.yaml
#    depend: [ "index" ]
#    map:
#      uri: '{workflow->files}'
#      regex: (.*)_(R|)1(.*)\.((fastq|fq)(|\.gz))$
#    template:
#      input: '{workflow->files}/{1}_{2}1{3}.{4}'
#      pair: '{workflow->files}/{1}_{2}2{3}.{4}'
#      reference: '{index->output}/reference'
#      threads: '{workflow->threads}'
#      output: '{1}.sam'
...
